name: SimpleNick
version: 0.1
main: Chillato\SimpleNick
author: ChillatoDev
api: 4.0.0

commands:
  nick:
    permission: simplenick.use
    description: "set a nick"
  nickreset:
    permission: nick.use
    description: "reset your nick"

permissions:
  simplenick.use:
    description:
    default: op
